name: Compile TWRP for cancunn

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Device Tree
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib3ncurses5-dev lib32z1-dev libelf-dev libfontconfig1-dev libgl1-mesa-dev libgusb-dev libpcap-dev libpulse-dev libreadline-dev libsdl1.2-dev libssl-dev libtool libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev zip

      - name: Sync TWRP Source
        working-directory: twrp_workspace
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.twrp -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Build Recovery Image
        run: |
          cd twrp_workspace
          source build/envsetup.sh
          lunch twrp_cancunn-eng
          mka recoveryimage

      - name: Upload Recovery Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-cancunn-Recovery
          path: twrp_workspace/out/target/product/cancunn/recovery.img
